### ISSUE TITLE
Download into .hitchpkg directory and use a specified version of firefox

### ISSUE THREAD

**Issue by crdoconnor** [hitchtest/hitchselenium#3]
- In order to prevent errors caused by the selenium library being incompatible with versions of firefox newly upgraded by the system package manager.
- To allow for replication of bugs caused by specific versions of firefox.

See : https://github.com/hitchtest/hitch/issues/29

**Comment by badri** [comment]
Hi, I get the following error with the latest Hitch/Hitchselenium:

```
[        Err Firefox] Traceback (most recent call last):
[        Err Firefox]   File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
[        Err Firefox]     "__main__", mod_spec)
[        Err Firefox]   File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
[        Err Firefox]     exec(code, run_globals)
[        Err Firefox]   File "/home/lakshmi/cf/panel/tests/.hitch/virtualenv/lib/python3.4/site-packages/hitchselenium/server.py", line 43, in <module>
[        Err Firefox]     run()
[        Err Firefox]   File "/home/lakshmi/cf/panel/tests/.hitch/virtualenv/lib/python3.4/site-packages/hitchselenium/server.py", line 26, in run
[        Err Firefox]     firefox_binary=FirefoxBinary(firefox_path=sys.argv[1])
[        Err Firefox]   File "/home/lakshmi/cf/panel/tests/.hitch/virtualenv/lib/python3.4/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
[        Err Firefox]     self.binary, timeout)
[        Err Firefox]   File "/home/lakshmi/cf/panel/tests/.hitch/virtualenv/lib/python3.4/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
[        Err Firefox]     self.binary.launch_browser(self.profile, timeout=timeout)
[        Err Firefox]   File "/home/lakshmi/cf/panel/tests/.hitch/virtualenv/lib/python3.4/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
[        Err Firefox]     self._wait_until_connectable(timeout=timeout)
[        Err Firefox]   File "/home/lakshmi/cf/panel/tests/.hitch/virtualenv/lib/python3.4/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 99, in _wait_until_connectable
[        Err Firefox]     "The browser appears to have exited "
[        Err Firefox] selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

Did I miss any step?

**Comment by colmoconnor-loveholidays** [comment]
No, this feature isn't finished yet so the system version of firefox is used by default. Unfortunately the latest version of selenium doesn't like the latest version of firefox.

If you downgrade the system firefox to the previous it it should work. Alternatively wait a few days and I will have a fix out.

**Comment by crdoconnor** [comment]
No, this feature isn't finished yet so the system version of firefox is used by default. Unfortunately the latest version of selenium doesn't like the latest version of firefox.

If you downgrade the system firefox to the previous it it should work. Alternatively wait a few days and I will have a fix out (I will comment here when it's ready).

**Comment by badri** [comment]
Awesome, let me know if I can help in this regard.

**Comment by crdoconnor** [comment]
Hi,

I've finished the feature. You can activate it by upgrading to the latest version -- 0.5.4- like so::

```
hitch install hitchselenium
```

Then, changing the code and putting this in your set up somewhere::

```
firefox_package = hitchselenium.FirefoxPackage()
firefox_package.build()
```

And adding the parameter firefox_binary to the service, e.g. like so::

```
self.services['Firefox'] = hitchselenium.SeleniumService(
        xvfb=self.settings.get("xvfb", False) or self.settings.get("quiet", False),
        no_libfaketime=True,
        firefox_binary=firefox_package.firefox,
)
```

If that works (and especially if it doesn't!), it'd be awesome if you could drop a note here letting me know.

This ought to work both on Mac and Linux.

**Comment by bodgerbarnett** [comment]
This worked for me - thanks.
